#
#spring:
#  profiles:
#    active: dev

spring:
  messages:
    basename: i18n.login

#logging:
#  #设置日志等级，需要指定包名
#  level:
#    com.nihfkeol: trace
#  file:
#    #不指定路径在当前项目下生成Spring.log日志
#    name: my.log
#    #可以指定完整路径
#    #name: G:/my.log
#    #在当前磁盘的根路径下创建SpringLogging文件夹和里面的log文件夹；使用spring.log作为默认文件
#    path: /SpringLogging/log



---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8086
spring:
  profiles: prod